<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Vsourz\HotDeals\Block\Widget\Hotdeals
 */


?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';
    $fix = $this->getFix();
    $id = $this->getId();
    $css = $this->getCss();
    if($this->getOptions()) {
        $options = trim($this->getOptions());
    }
    else {
        $options = "{loop:true,autoplay:false,items:2}";
        // $options = "{loop:true,autoplay:false,center:false,mouseDrag:true,touchDrag:true,pullDrag:true,freeDrag:true,margin:0,stagePadding:0,merge:false,mergeFit:true,autoWidth:false,startPosition:0,rtl:false,smartSpeed:500,fluidSpeed:500,dragEndSpeed:500,responsive:{0:{items:1},320:{items:1},375:{items:1},414:{items:1},480:{items:1},568:{items:1},667:{items:1},736:{items:1},750:{items:1},768:{items:1},1024:{items:1},1200:{items:1},1250:{items:1}},responsiveRefreshRate:200,responsiveBaseElement:window,responsiveClass:true,fallbackEasing:'swing',info:false,nestedItemSelector:false,itemElement:'div',stageElement:'div',themeClass:'owl-theme',baseClass:'owl-carousel',itemClass:'owl-item',centerClass:'center',activeClass:'active'}";
    }
    $title = $this->getTitle();
    $mode = 'grid';
    $currencySymbol = $block->getStore()->getCurrentCurrency()->getCurrencySymbol();

    // $image = 'category_page_list';
    // $image = 'new_products_content_widget_grid';
    $image = 'category_page_list';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $productCollection = $block->getProductCollection();
    $productCollection->getSelect();
    // $items = $productCollection->getItems();



    /*
    ++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++
    ++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++
    */


    $categoriesString = $block->getCategories();

    $categoriesArray = explode(',', $categoriesString);
    // $categoriesArray = array($categoriesString);





    /*
    ++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++
    ++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++
    */


    $allProductCollection = $block->getProductsAllCollection();

    // $category = $block->getCategoryFactory()->create()->load('44');
    /*$arrAllCategoryProducts = array();
    $i = 0;
    foreach ($categoriesArray as $ctgr => $ctgrval) {
        $items = '';
        $temp = '';
        $temp = $block->getCategoryFactory()->create()->load($ctgrval);
        $allProductCollection1 = $allProductCollection->addCategoryFilter($temp);

        $items = $allProductCollection1->getItems();
        $arrAllCategoryProducts[$i] = $items;
        $i++;
    }*/

    // $allProductCollection->addCategoryFilter($category);


    // foreach($categoriesArray as $ctgry){
    //     $category[] = $this->getCategoryFactory()->create()->load($ctgry);
    //     $allProductCollection->addCategoryFilter($category[]);
    // }

    // echo "<pre>";


    $items = $allProductCollection->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $countdownStyle = "style-1";
    $htmlCountdown = '<div class="countdown '.$countdownStyle .'" >';
    //$htmlCountdown .= '<span class="countdown-section sec-week"><span class="countdown-amount">%w</span> <span class="countdown-text">week%!w</span></span>';
    $htmlCountdown .= '<span class="countdown-section sec-day"><span class="countdown-amount">%d </span><span class="countdown-text">day%!d</span></span>';
    $htmlCountdown .= '<span class="countdown-section sec-hour"><span class="countdown-amount">%H</span><span class="countdown-text"> hour%!H </span></span>';
    $htmlCountdown .= '<span class="countdown-section"><span class="countdown-amount">%M</span><span class="countdown-text sec-minute"> minute%!M </span></span>';
    $htmlCountdown .= '<span class="countdown-section sec-second"><span class="countdown-amount">%S </span><span class="countdown-text">second%!S</span></span>';
    $htmlCountdown .= '</div>';
?>
    <div class="block widget block-products-list hotdeals-slider-block <?php /* @escapeNotVerified */ echo $mode; ?> comman-hot-deal">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol id="<?php echo $id;?>" class="product-items <?php /* @escapeNotVerified */ echo $type; ?> hotdeals-slider-ul">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php
                            // this is template data
                            $specialPrice = $block->getSpecialPrice($_item);
                            $normalPrice = $block->getNormalPrice($_item);
                            $yousave = $block->getSavedAmount($_item);
                            $discountPercent = $block->getDiscountPercent($_item);
                        ?>

                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item hotdeals-item hotdeals-slider-li">' : '</li><li class="product-item hotdeals-item hotdeals-slider-li">' ?>
                        <div class="product-item-info1 hotdeals-slider-li-inner">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                <?php //print_r(get_class_methods($_item->getImage())) ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php echo $block->getProductPriceHtml($_item, $type); ?>

                                <div class="hot-discount">
                                    <span class="hot-label"> <?php echo __('Discount :')?>  </span>
                                    <span class="hot-data"><?php echo $discountPercent . "%"; ?></span>
                                </div>
                                <div class="hot-yousave">
                                    <span class="hot-label"><?php echo __('You save :')?>  </span>
                                    <span class="hot-data"><?php echo $currencySymbol . $yousave; ?></span>
                                </div>
                                <!--<div class="hotdeals-review">
                                <?php // echo $block->getReviewsSummaryHtml($_item, 'short',true); ?>
                                </div>-->
                                <div data-countdown="<?php echo date('Y/m/d', strtotime($_item['special_to_date'])); ?>" data-html='<?php echo $htmlCountdown; ?>' class="timer hotdeal-timer"></div>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action fa fa-heart-o" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action fa fa-signal"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<script type="text/javascript" charset="utf-8">
    require([
        'jquery',
        'owlCarousel',
        'countdown'
    ], function ($) {
        'use strict';

        $(document).ready(function(){
            $('#<?php echo $id;?>').owlCarousel(<?php echo $options;?>);

            $('[data-countdown]').each(function(index,el) {
                 $(this).countdown($(this).data('countdown'), function(event) {
                    $(this).html(event.strftime($(this).data('html')));
                });
            });

            $('#<?php echo $id;?>').on('changed.owl.carousel', function(event) {
                $('[data-countdown]').each(function(index,el) {
                    $(this).countdown($(this).data('countdown'), function(event) {
                        $(this).html(event.strftime($(this).data('html')));
                    });
                });
            });

        });

    });
</script>
<?php endif;?>
